project_name: My Project
roots:
# Role
-   name: role
    data_ref: role_list
    list_columns: [ name , actions]
    form:  
        -   name: name
            widget: text
            validators:  required
        -   actions
# User
-   name: user
    label_prop: username
    labels: 
        username: Username
        first_name: First Name
        last_name: Last Name
    list_columns: [ username , first_name, last_name]
    form: 
        -   first_name
        -   last_name
        -   name: username
            validators: required
#Apps
-   name: app
    label: Application
    list_columns: [ name, desc ]
    pk_prop: _id
    pk_type: 
    form: 
        -   name: name
            validators: required
        -   desc
        -   iconUrl

#events
-   name: event
    list_columns: 
        -   time 
        -   image:
                as: img
                style: width:100px  
        -   name:
                as: href
        -   description
    pk_prop: _id
    pk_type: 
    form: 
        -   name: time
            validators: required
        -   name: name
            validators: required
        -   name: description
            widget: richtext
        -   name: image




# Collections
data:
    role_list: 
        -   name: Admin
            actions: read,write
            id: 1
        -   name: User
            actions: read
            id: 2
    app:
        db_name: test
        col_name: apps

    event:
        db_name: test
        col_name: b_news
